// Resolves Fotmob crest/face images (scraped + fuzzy-matched to Opta ids) to
// public asset paths. The map is generated by build_image_map.py.
import imageMap from "../../public/data/imageMap.json";

type ImageMap = {
  teams: Record<string, string>;
  teamNames: Record<string, string>;
  players: Record<string, string>;
  playerNames: Record<string, string>;
};

const map = imageMap as unknown as ImageMap;

/** Team crest by Opta team id. */
export function teamCrest(teamId?: string | null): string | null {
  return teamId ? map.teams[teamId] ?? null : null;
}

/** Team crest by Opta team display name (e.g. "Argentina"). */
export function teamCrestByName(name?: string | null): string | null {
  return name ? map.teamNames[name] ?? null : null;
}

/** Player face by Opta player id. */
export function playerFace(playerId?: string | null): string | null {
  return playerId ? map.players[playerId] ?? null : null;
}

/** Player face by Opta player display name (e.g. "L. Messi"). */
export function playerFaceByName(name?: string | null): string | null {
  return name ? map.playerNames[name] ?? null : null;
}

/** Initials fallback when no face/crest is available. */
export function initials(name?: string | null): string {
  if (!name) return "?";
  const parts = name.replace(/\./g, "").trim().split(/\s+/).filter(Boolean);
  if (parts.length === 0) return "?";
  if (parts.length === 1) return parts[0].slice(0, 2).toUpperCase();
  return (parts[0][0] + parts[parts.length - 1][0]).toUpperCase();
}
